services:
  - type: web
    name: ave-catering-api
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    rootDir: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
